'use strict';
const assert = require('assert/strict');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { spawnSync } = require('child_process');
const [expected, sourceArg] = process.argv.slice(2);
assert.match(expected || '', /^[a-f0-9]{40}$/);
assert.ok(sourceArg, 'Pass expected SHA and validated package root');
const source = path.resolve(sourceArg);
const out = path.resolve(process.env.AUDIT_OUTPUT || 'output/unity-mcp-install-2026-09-09');
const readJson = p => JSON.parse(fs.readFileSync(p, 'utf8').replace(/^\uFEFF/, ''));
const id = 'com.community.unity-mcp';
const dependency = readJson('Packages/manifest.json').dependencies[id];
assert.equal(dependency, 'https://github.com/Seoki2000/unity-mcp.git#' + expected);
const locked = readJson('Packages/packages-lock.json').dependencies[id];
assert.equal(locked.version, dependency);
assert.equal(locked.hash, expected);
const head = spawnSync('git', ['-c', 'safe.directory=' + source, '-C', source, 'rev-parse', 'HEAD'], { encoding: 'utf8' });
assert.equal(head.status, 0, head.stderr);
assert.equal(head.stdout.trim(), expected);
const candidates = fs.readdirSync('Library/PackageCache').filter(n => n.startsWith(id + '@') && expected.startsWith(n.slice(id.length + 1)));
assert.equal(candidates.length, 1, 'Expected one cache for selected SHA');
const installed = path.resolve('Library/PackageCache', candidates[0]);
const digest = p => crypto.createHash('sha256').update(fs.readFileSync(p, 'utf8').replace(/\r\n/g, '\n')).digest('hex');
const checks = [];
for (const file of ['Bridge/mcp-bridge.js', 'Bridge/mcp-bridge-launcher.js', 'Bridge/index/scan.js', 'Bridge/index/tools.js', 'Bridge/index/errorimpact.js']) {
  const actual = digest(path.join(installed, file));
  assert.equal(actual, digest(path.join(source, file)), file + ' differs from verified source');
  checks.push({ file, sha256NormalizedText: actual });
}
const launcher = readJson('.mcp.json').mcpServers.unity.args[0];
assert.equal(digest(launcher), digest(path.join(source, 'Bridge/mcp-bridge-launcher.js')));
const live = readJson(path.join(out, 'live-results.json'));
assert.equal(live.ok, true, 'Installed live checks failed');
assert.ok(live.launcherLog.replace(/\\/g, '/').includes(installed.replace(/\\/g, '/') + '/Bridge/mcp-bridge.js'), 'Launcher did not report selected cache path');
assert.equal(live.stdio.find(x => x.name === 'tools/list').count, 85);
const result = { at: new Date().toISOString(), expected, dependency, installed, launcher, checks, liveVerified: true, ok: true };
fs.writeFileSync(path.join(out, 'installation-verification.json'), JSON.stringify(result, null, 2));
console.log(JSON.stringify(result, null, 2));
